plugins { id 'com.android.application' }

android {
    namespace 'com.mrt.jarvis.installertest'
    compileSdk 33

    defaultConfig {
        applicationId 'com.mrt.jarvis.installertest'
        minSdk 21
        targetSdk 28
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
